### ISSUE TITLE
Bug report on the False Positives feature

### ISSUE THREAD

**Issue by anushasquadcast** [roshan8/slo-tracker#10]
What is currently happening:

1. An incident is created in the dashboard for an alert in one of the available monitoring tools
2. The incident is in open state
3. The incident is marked as a false positive post analysis
4. The incident still remains in the open state

What should happen:

1. An incident is created in the dashboard for an alert in one of the available monitoring tools
2. The incident is in open state
3. The incident is marked as a false positive post analysis
4. The incident is moved to closed state

Why should the behaviour change:
The incident still should be moved to closed state since it is irrelevant when marked as a false positive and should not be accounted towards the error budget calculations or analytics

**Comment by roshan8** [comment]
Thanks for reporting!
This is addressed in https://github.com/roshan8/slo-tracker/commit/450f9184d8fda74e2f99ca9c853691e4e15fbbe5
