### ISSUE TITLE
MySQL connection strings hard-coded throughout

### ISSUE THREAD

**Issue by johnseekins** [roshan8/slo-tracker#13]
Even though environment variables are available, we still end up using strings like: 
```
    dbConnectionString := fmt.Sprintf("root:SecretPassword@tcp(%s:3306)/", config.DBHost)
```
which is really _only_ valid for MySQL. It would be nice to make this all more flexible. At least allowing for sqlite installations for easier testing.

**Comment by roshan8** [comment]
Closing this issue since #14 has been merged.

**Comment by johnseekins** [comment]
I'm a bit confused by this being closed. I see a `tcp` connection string still hard-coded, which means no option for sqlite still. If this is the intention, that's fine, but...
