### ISSUE TITLE
Add integration with VictoriaMetrics

### ISSUE THREAD

**Issue by valyala** [roshan8/slo-tracker#16]
It would be great if slo-tracker could integrate with [VictoriaMetrics](https://github.com/VictoriaMetrics/VictoriaMetrics/) + [vmalert](https://docs.victoriametrics.com/vmalert.html).

**Comment by roshan8** [comment]
@valyala Thanks for submitting the request.
I have a bunch of other things to work on so I can’t work on this anytime soon. I’d be happy to take a look at a patch for this!
