### ISSUE TITLE
Running npm install react-scripts failed

### ISSUE THREAD

**Issue by vcheruk2** [roshan8/slo-tracker#19]
Step 6/14 : RUN npm install react-scripts --save -legacy-peer-deps
 ---> Running in c8d0aa420339
npm ERR! code ERR_SOCKET_TIMEOUT
npm ERR! errno ERR_SOCKET_TIMEOUT
npm ERR! network Invalid response body while trying to fetch https://registry.npmjs.org/rc-tree: Socket timeout
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-01T13_40_04_573Z-debug-0.log
The command '/bin/sh -c npm install react-scripts --save -legacy-peer-deps' returned a non-zero code: 1
ERROR: Service 'slo-fe' failed to build : Build failed

I see network-related errors/timeouts but my internet connectivity is solid.

**Comment by yashjain77** [comment]
You can try using `-timeout=60000`flag, and see if it works.

**Comment by roshan8** [comment]
Please reopen the issue if the issue still persist.
